# CONFIGURACION DEL SERVIDOR
spring.application.name=ProyectoCarrito
server.port=${PORT:8080}

# CONFIGURACION DE BD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# LA SESION DE JPA/HIBERNATE NO PERMACERA ABIERTA DURANTE TODO EL
# CICLO DE VIDA DE UNA SOLICITUD HTTP
spring.jpa.open-in-view=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# CONFIGURACION DE JWT
jwt.secret=${JWT_SECRET}

# TIEMPO EXPIRACION (1 HORA)
jwt.expiration=${JWT_EXPIRATION:3600000}

